package com.example.db.model;
// Generated Mar 26, 2024, 4:13:48 AM by Hibernate Tools 6.3.1.Final

import java.sql.Date;

/**
 * Reservationdetail generated by hbm2java
 */
public class Reservationdetail implements java.io.Serializable {

	private Integer rdId;
	private reservation reservation;
	private Date date;

	public Reservationdetail() {
	}

	public Reservationdetail(reservation reservation, Date date) {
		this.reservation = reservation;
		this.date = date;
	}

	public Integer getRdId() {
		return this.rdId;
	}

	public void setRdId(Integer rdId) {
		this.rdId = rdId;
	}

	public reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(reservation reservation) {
		this.reservation = reservation;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
